#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar main:20:0

# global settings
yabai -m config     \
    mouse_follows_focus          on \
    focus_follows_mouse          autofocus \
    window_placement             second_child \
    window_topmost               on \
    window_shadow                on \
    window_opacity               off \
    window_animation_duration    0.0 \
    window_opacity_duration      0.0 \
    active_window_opacity        1.0 \
    normal_window_opacity        0.90  \
    window_border                off  \
    window_border_width          2  \
    window_border_radius         12  \
    window_border_blur           off \
    window_border_hidpi          on  \
    active_window_border_color   0xff775759 \
    normal_window_border_color   0xff555555 \
    insert_feedback_color        0xaad75f5f  \
    split_ratio                  0.50 \
    split_type                   auto \
    auto_balance                 on \
    mouse_modifier               fn \
    mouse_action1                move \
    mouse_action2                resize \
    mouse_drop_action            swap \
    layout                       bsp \
    top_padding                  16 \
    bottom_padding               10 \
    left_padding                 10 \
    right_padding                10 \
    window_gap                   10

# mission-control desktop labels
yabai -m space 1
yabai -m space 2
yabai -m space 3
yabai -m space 4
yabai -m space 5
yabai -m space 6
yabai -m space 7
yabai -m space 8
yabai -m space 9

# specific space settings
# yabai -m config --space mail layout stack

# window rules
yabai -m rule --add app="^Firefox$" space=2
# yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
yabai -m rule --add app="^Discord$" space=6
yabai -m rule --add app="^Slack$" space=6
yabai -m rule --add app="^Element$" space=6
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Viscosity$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Reverso$" manage=off

echo "yabai configuration loaded.."
